//! Opaque identifier newtypes.
//!
//! Each variant wraps a non-empty `String`. None of these IDs carry
//! invariants beyond non-emptiness — they are server-generated or
//! caller-supplied opaque values the SDK preserves verbatim.
//!
//! The types are generated by a shared `id_newtype!` macro because they
//! have **identical structure** (non-empty string, `new` + `as_str` +
//! `Display`, transparent serde, per-type `Invalid*` error). The macro
//! enforces uniformity: no two identifiers can drift in their surface,
//! and adding a new one is a one-line invocation. The type system still
//! distinguishes them at every call site — passing a `MessageId` where
//! a `RequestId` is expected is a compile error, which is the whole
//! reason for newtyping in the first place.

/// Generate a non-empty `String` identifier newtype with the standard
/// surface: validating `new`, `as_str`, `Display`, transparent serde,
/// and a per-type `Invalid*` thiserror struct.
///
/// Arguments:
/// - `$name` — newtype identifier (e.g. `RequestId`)
/// - `$err`  — companion error struct identifier (e.g. `InvalidRequestId`)
/// - `$doc`  — type-level rustdoc literal
/// - `$err_msg` — error message literal used by `thiserror` (must be a
///   string literal, not a macro expression — `thiserror`'s `#[error]`
///   attribute does not expand nested macros).
macro_rules! id_newtype {
    ($name:ident, $err:ident, $doc:literal, $err_msg:literal) => {
        #[doc = $doc]
        #[derive(Clone, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
        #[serde(transparent)]
        pub struct $name(String);

        #[doc = concat!("Reason [`", stringify!($name), "::new`] can reject input.")]
        #[derive(Debug, Clone, thiserror::Error, PartialEq, Eq)]
        #[error($err_msg)]
        pub struct $err;

        impl $name {
            /// Validate and wrap a string as this identifier.
            ///
            /// # Errors
            /// Returns the corresponding empty-value error when `s` is empty.
            pub fn new(s: impl Into<String>) -> Result<Self, $err> {
                let s = s.into();
                if s.is_empty() { Err($err) } else { Ok(Self(s)) }
            }

            /// Borrow the validated identifier for wire-format use.
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&self.0)
            }
        }
    };
}

id_newtype!(
    RequestId,
    InvalidRequestId,
    "Opaque server-generated request identifier from the `request-id` response header.",
    "RequestId must not be empty"
);
id_newtype!(
    MessageId,
    InvalidMessageId,
    "Opaque server-generated `id` field of a message response.",
    "MessageId must not be empty"
);
id_newtype!(
    ToolUseId,
    InvalidToolUseId,
    "Server-generated identifier that correlates a `tool_use` block with the matching `tool_result`.",
    "ToolUseId must not be empty"
);
id_newtype!(
    ToolName,
    InvalidToolName,
    "Caller-supplied tool name passed in a `Tool` definition.",
    "ToolName must not be empty"
);
id_newtype!(
    OrganizationId,
    InvalidOrganizationId,
    "Opaque organization identifier from the `anthropic-organization-id` response header.",
    "OrganizationId must not be empty"
);
id_newtype!(
    UserId,
    InvalidUserId,
    "Caller-supplied end-user identifier sent in `metadata.user_id`.",
    "UserId must not be empty"
);
id_newtype!(
    StopSequence,
    InvalidStopSequence,
    "Stop sequence supplied via `stop_sequences` on a `MessageRequest`.",
    "StopSequence must not be empty"
);

#[cfg(test)]
mod tests {
    #![expect(
        clippy::unwrap_used,
        reason = "tests unwrap known-valid fixtures; a panic is the intended failure signal"
    )]

    use super::*;

    #[test]
    fn each_id_rejects_empty() {
        assert!(RequestId::new("").is_err());
        assert!(MessageId::new("").is_err());
        assert!(ToolUseId::new("").is_err());
        assert!(ToolName::new("").is_err());
        assert!(OrganizationId::new("").is_err());
        assert!(UserId::new("").is_err());
        assert!(StopSequence::new("").is_err());
    }

    #[test]
    fn each_id_accepts_typical_value() {
        assert!(RequestId::new("req_abcdef").is_ok());
        assert!(MessageId::new("msg_abcdef").is_ok());
        assert!(ToolUseId::new("toolu_abcdef").is_ok());
        assert!(ToolName::new("get_weather").is_ok());
        assert!(OrganizationId::new("org_abcdef").is_ok());
        assert!(UserId::new("user-42").is_ok());
        assert!(StopSequence::new("STOP").is_ok());
    }

    #[test]
    fn serde_transparent_round_trip() {
        let id = MessageId::new("msg_abc").unwrap();
        let j = serde_json::to_string(&id).unwrap();
        assert_eq!(j, "\"msg_abc\"");
        let back: MessageId = serde_json::from_str(&j).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn display_matches_as_str() {
        let id = RequestId::new("req_xyz").unwrap();
        assert_eq!(format!("{id}"), id.as_str());
    }
}
